/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiAiDoubtRouteImport } from './routes/api/ai/doubt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDoubtRoute = ApiAiDoubtRouteImport.update({
  id: '/api/ai/doubt',
  path: '/api/ai/doubt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/courses': typeof CoursesRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/my-learning': typeof MyLearningRoute
  '/profile': typeof ProfileRoute
  '/api/ai/doubt': typeof ApiAiDoubtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/courses': typeof CoursesRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/my-learning': typeof MyLearningRoute
  '/profile': typeof ProfileRoute
  '/api/ai/doubt': typeof ApiAiDoubtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/courses': typeof CoursesRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/my-learning': typeof MyLearningRoute
  '/profile': typeof ProfileRoute
  '/api/ai/doubt': typeof ApiAiDoubtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/books'
    | '/courses'
    | '/home'
    | '/live'
    | '/my-learning'
    | '/profile'
    | '/api/ai/doubt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/books'
    | '/courses'
    | '/home'
    | '/live'
    | '/my-learning'
    | '/profile'
    | '/api/ai/doubt'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/books'
    | '/courses'
    | '/home'
    | '/live'
    | '/my-learning'
    | '/profile'
    | '/api/ai/doubt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRoute
  CoursesRoute: typeof CoursesRoute
  HomeRoute: typeof HomeRoute
  LiveRoute: typeof LiveRoute
  MyLearningRoute: typeof MyLearningRoute
  ProfileRoute: typeof ProfileRoute
  ApiAiDoubtRoute: typeof ApiAiDoubtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/doubt': {
      id: '/api/ai/doubt'
      path: '/api/ai/doubt'
      fullPath: '/api/ai/doubt'
      preLoaderRoute: typeof ApiAiDoubtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRoute,
  CoursesRoute: CoursesRoute,
  HomeRoute: HomeRoute,
  LiveRoute: LiveRoute,
  MyLearningRoute: MyLearningRoute,
  ProfileRoute: ProfileRoute,
  ApiAiDoubtRoute: ApiAiDoubtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
