// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const isSupabaseConfigured = Boolean(
  ((typeof import.meta !== "undefined" && import.meta.env?.["VITE_SUPABASE_URL"]) ||
    (typeof process !== "undefined" && process.env?.["SUPABASE_URL"])) &&
  ((typeof import.meta !== "undefined" && import.meta.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"]) ||
    (typeof process !== "undefined" && process.env?.["SUPABASE_PUBLISHABLE_KEY"])),
);

function createFallbackQueryBuilder(): unknown {
  const handler: ProxyHandler<object> = {
    get(_target, prop) {
      if (prop === "then") {
        return (resolve: (res: { data: unknown[]; error: null; count: number }) => unknown) =>
          Promise.resolve({ data: [], error: null, count: 0 }).then(resolve);
      }
      if (prop === "catch") {
        return (reject: (reason: unknown) => unknown) =>
          Promise.resolve({ data: [], error: null, count: 0 }).catch(reject);
      }
      if (prop === "single" || prop === "maybeSingle") {
        return () => Promise.resolve({ data: null, error: null });
      }
      return () => new Proxy({}, handler);
    },
  };
  return new Proxy({}, handler);
}

function createFallbackSupabaseClient() {
  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      onAuthStateChange: (_callback: unknown) => ({
        data: {
          subscription: {
            id: "guest-mode",
            callback: () => {},
            unsubscribe: () => {},
          },
        },
        error: null,
      }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: new Error(
          "Supabase authentication is not configured yet. You can continue as a guest to access all batches, lectures, and notes.",
        ),
      }),
      signUp: async () => ({
        data: { user: null, session: null },
        error: new Error(
          "Supabase authentication is not configured yet. You can continue as a guest to access all batches, lectures, and notes.",
        ),
      }),
      signOut: async () => ({ error: null }),
      setSession: async () => ({ data: { session: null }, error: null }),
      resetPasswordForEmail: async () => ({ data: null, error: null }),
    },
    from: (_table: string) => createFallbackQueryBuilder(),
    storage: {
      from: (_bucket: string) => ({
        getPublicUrl: (filePath: string) => ({ data: { publicUrl: filePath } }),
        upload: async () => ({ data: null, error: new Error("Storage not configured") }),
        download: async () => ({ data: null, error: new Error("Storage not configured") }),
      }),
    },
    functions: {
      invoke: async () => ({ data: null, error: new Error("Functions not configured") }),
    },
    channel: (_name: string) => ({
      on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }),
      subscribe: () => ({ unsubscribe: () => {} }),
      unsubscribe: () => {},
    }),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createFallbackSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
